#!/usr/bin/env bun
/**
 * Interactive Odoo connection wizard.
 *
 *   bun run setup
 *
 * Walks the user through ODOO_URL / ODOO_DB / ODOO_USER / credentials
 * and writes them to ~/.odoocli/odoo.env (mode 0600). The startup
 * plugin (plugins/odoo-env.ts) loads that file on every launch.
 *
 * Distinct from the plugin: the plugin runs in opencode's server
 * process where stdin is not always a TTY, so it can only read a
 * file. This script is invoked explicitly by the user from a shell,
 * so it can prompt interactively. The two share one file format.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { homedir } from "node:os"
import { join } from "node:path"

// Note: this script uses Bun's built-in `prompt()` global instead of
// node:readline. The latter has a known issue under bun where the second
// `rl.question()` call hangs when stdin is non-TTY (heredoc, file
// redirect, CI). Bun's `prompt()` handles both TTY and piped stdin
// consistently and is part of the standard Bun runtime.
declare function prompt(message?: string, defaultValue?: string): string | null

const ODOOCLI_HOME = process.env.ODOOCLI_HOME ?? join(homedir(), ".odoocli")
const ENV_FILE = join(ODOOCLI_HOME, "odoo.env")

type Creds = {
  ODOO_URL?: string
  ODOO_DB?: string
  ODOO_USER?: string
  ODOO_PASSWORD?: string
  ODOO_API_KEY?: string
}

function parseEnvFile(text: string): Creds {
  const out: Creds = {}
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim()
    if (!line || line.startsWith("#")) continue
    const eq = line.indexOf("=")
    if (eq <= 0) continue
    const key = line.slice(0, eq).trim() as keyof Creds
    let value = line.slice(eq + 1).trim()
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }
    if (value) out[key] = value
  }
  return out
}

function loadCurrent(): Creds {
  const fromFile = existsSync(ENV_FILE) ? parseEnvFile(readFileSync(ENV_FILE, "utf8")) : {}
  // Shell exports win in the live env, but for the wizard we surface
  // both so the user sees what's already in effect.
  return {
    ODOO_URL: process.env.ODOO_URL ?? fromFile.ODOO_URL,
    ODOO_DB: process.env.ODOO_DB ?? fromFile.ODOO_DB,
    ODOO_USER: process.env.ODOO_USER ?? fromFile.ODOO_USER,
    ODOO_PASSWORD: process.env.ODOO_PASSWORD ?? fromFile.ODOO_PASSWORD,
    ODOO_API_KEY: process.env.ODOO_API_KEY ?? fromFile.ODOO_API_KEY,
  }
}

function masked(value: string | undefined): string {
  if (!value) return "(unset)"
  if (value.length <= 4) return "•".repeat(value.length)
  return value.slice(0, 2) + "•".repeat(value.length - 4) + value.slice(-2)
}

function quoteIfNeeded(value: string): string {
  // Quote when the value contains whitespace or # so the file parser is happy
  return /[\s#]/.test(value) ? `"${value.replace(/"/g, '\\"')}"` : value
}

function renderEnvFile(creds: Creds): string {
  const lines: string[] = [
    "# OdooCLI connection settings",
    "# Generated by `bun run setup`. Edit by hand or re-run the wizard.",
    "# Anything you `export` in your shell takes precedence over this file.",
    "",
  ]
  if (creds.ODOO_URL) lines.push(`ODOO_URL=${quoteIfNeeded(creds.ODOO_URL)}`)
  if (creds.ODOO_DB) lines.push(`ODOO_DB=${quoteIfNeeded(creds.ODOO_DB)}`)
  if (creds.ODOO_USER) lines.push(`ODOO_USER=${quoteIfNeeded(creds.ODOO_USER)}`)
  if (creds.ODOO_PASSWORD) lines.push(`ODOO_PASSWORD=${quoteIfNeeded(creds.ODOO_PASSWORD)}`)
  if (creds.ODOO_API_KEY) lines.push(`ODOO_API_KEY=${quoteIfNeeded(creds.ODOO_API_KEY)}`)
  lines.push("")
  return lines.join("\n")
}

function bail(message: string, code = 1): never {
  console.error(`\n❌ ${message}`)
  process.exit(code)
}

function ask(label: string, current?: string): string | undefined {
  const hint = current ? ` [${current}]` : ""
  const answer = (prompt(`${label}${hint}:`) ?? "").trim()
  return answer || current
}

function askSecret(label: string, current?: string): string | undefined {
  // Input is visible. Hiding stdin in a portable way needs raw-mode
  // gymnastics; not worth the dep for a one-shot wizard. The file we write
  // is mode 0600, so the persisted value is at least not world-readable.
  const display = current ? ` [${masked(current)}]` : ""
  const answer = (prompt(`${label}${display}:`) ?? "").trim()
  return answer || current
}

function main() {
  console.log()
  console.log("─────────────────────────────────────────────────────────────")
  console.log(" OdooCLI — Odoo connection setup")
  console.log("─────────────────────────────────────────────────────────────")
  console.log(` Writing to ${ENV_FILE}`)
  console.log(` Press Enter to keep the existing value shown in [brackets].`)
  console.log()

  const current = loadCurrent()
  const next: Creds = {}

  next.ODOO_URL = ask("ODOO_URL         ", current.ODOO_URL)
  if (!next.ODOO_URL) bail("ODOO_URL is required.")
  if (!/^https?:\/\//.test(next.ODOO_URL)) {
    console.warn(`  ⚠  ${next.ODOO_URL} doesn't look like a URL — make sure it starts with http:// or https://`)
  }

  next.ODOO_DB = ask("ODOO_DB          ", current.ODOO_DB)
  if (!next.ODOO_DB) bail("ODOO_DB is required.")

  next.ODOO_USER = ask("ODOO_USER        ", current.ODOO_USER ?? "admin")
  if (!next.ODOO_USER) bail("ODOO_USER is required.")

  console.log()
  console.log(" Authentication: pick one")
  console.log("   1) ODOO_PASSWORD  — Odoo 17–18, or any version")
  console.log("   2) ODOO_API_KEY   — Odoo 19+ (recommended, generate in Settings → Users)")
  const defaultChoice = current.ODOO_API_KEY ? "2" : "1"
  const choice = (prompt(` Choice [${defaultChoice}]:`) ?? "").trim() || defaultChoice
  console.log()

  if (choice === "2") {
    next.ODOO_API_KEY = askSecret("ODOO_API_KEY     ", current.ODOO_API_KEY)
    if (!next.ODOO_API_KEY) bail("ODOO_API_KEY is required when you pick option 2.")
    next.ODOO_PASSWORD = undefined
  } else {
    next.ODOO_PASSWORD = askSecret("ODOO_PASSWORD    ", current.ODOO_PASSWORD)
    if (!next.ODOO_PASSWORD) bail("ODOO_PASSWORD is required when you pick option 1.")
    next.ODOO_API_KEY = undefined
  }

  console.log()
  console.log("─────────────────────────────────────────────────────────────")
  console.log(" Review")
  console.log("─────────────────────────────────────────────────────────────")
  console.log(`  ODOO_URL      = ${next.ODOO_URL}`)
  console.log(`  ODOO_DB       = ${next.ODOO_DB}`)
  console.log(`  ODOO_USER     = ${next.ODOO_USER}`)
  if (next.ODOO_PASSWORD) console.log(`  ODOO_PASSWORD = ${masked(next.ODOO_PASSWORD)}`)
  if (next.ODOO_API_KEY) console.log(`  ODOO_API_KEY  = ${masked(next.ODOO_API_KEY)}`)
  console.log()

  // Confirm before overwriting an existing file with different values.
  if (existsSync(ENV_FILE)) {
    const ok = (prompt(`Write to ${ENV_FILE}? [Y/n]`) ?? "").trim().toLowerCase()
    if (ok && ok !== "y" && ok !== "yes") {
      console.log("Aborted. Nothing written.")
      return
    }
  }

  mkdirSync(ODOOCLI_HOME, { recursive: true })
  writeFileSync(ENV_FILE, renderEnvFile(next), { mode: 0o600 })

  console.log()
  console.log(`✅ Wrote ${ENV_FILE} (mode 0600)`)
  console.log()
  console.log("Next steps:")
  console.log("  bun run dev          # launch OdooCLI on the odoo agent")
  console.log()
  console.log("To re-run this wizard later: bun run setup")
}

try {
  main()
} catch (err) {
  console.error(`\n❌ setup-odoo failed:`, err instanceof Error ? err.message : err)
  process.exit(1)
}
